### ISSUE TITLE
Trouble with installing into right Python home

### ISSUE THREAD

**Issue by mavam** [bro/broker#9]
I'm trying to setup a Python virtual env with Broker. It seems that the install step installs packages in the wrong destination. This is what I did:

Setup a Python virtual environment:

```shell
export PREFIX=$(pwd)/env
python3 -m venv $PREFIX
source $PREFIX/bin/activate
```

Then, install Broker:

```shell
git clone git@github.com:bro/broker.git
cd broker
git submodule update --recursive --init
./configure
  --generator=Ninja \
  --prefix=$PREFIX \
  --with-python=$PREFIX/bin/python
cd build
ninja
ninja install
```

The resulting directory layout:
```
ls $PREFIX/lib
python             libbroker.dylib           libcaf_io.dylib
python3.7          libcaf_core.0.15.7.dylib  libcaf_openssl.0.15.7.dylib
libbroker...dylib  libcaf_core.dylib         libcaf_openssl.dylib
libbroker.0.dylib  libcaf_io.0.15.7.dylib
```

Here, the problem is that the bindings are installed into `python` and not `python3.7`. The problem lies in the CMake script:

```cmake
if ( NOT PY_MOD_INSTALL_DIR )
  # Figure out Python module install directory.
  if (BROKER_PYTHON_PREFIX)
    set(pyver ${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR})
    set(PY_MOD_INSTALL_DIR
        ${BROKER_PYTHON_PREFIX}/lib/python${pyver}/site-packages)
  elseif (BROKER_PYTHON_HOME)
    set(PY_MOD_INSTALL_DIR ${BROKER_PYTHON_HOME}/lib/python)    <-------
  else ()
    execute_process(COMMAND ${PYTHON_EXECUTABLE} -c
      "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
      OUTPUT_VARIABLE python_site_packages
      OUTPUT_STRIP_TRAILING_WHITESPACE)
    set(PY_MOD_INSTALL_DIR ${python_site_packages})
  endif ()
endif ()
```

I'm not sure what the right fix is, though, but wanted to bring this issue to your attention.

**Comment by jsiwek** [comment]
If you use `--prefix`, Broker defaults to the "home scheme" type of python module installation and I think that's the intended location for that.  It looks like you can use `--python-prefix` to override that and install in the location that you want?

**Comment by mavam** [comment]
I've tried to read up on the notion of "home scheme" that says the modules go in `${BROKER_PYTHON_HOME}/lib/python`, but could not find such reference. I've encountered only the other scheme in [stackoverflow](https://stackoverflow.com/q/16196268/1170277) [posts](https://stackoverflow.com/q/122327/1170277) and [official docs](https://docs.python.org/3/tutorial/venv.html) `${BROKER_PYTHON_PREFIX}/lib/python${pyver}/site-packages)`.

**Comment by jsiwek** [comment]
> I've tried to read up on the notion of "home scheme" that says the modules go in ${BROKER_PYTHON_HOME}/lib/python, but could not find such reference. 

https://docs.python.org/3.7/install/#alternate-installation-the-home-scheme

It's using this install location just because you gave an explicit `--prefix`.  That can be an ambiguous situation since the typical install location for python modules in `site-packages/` can live outside the `--prefix` that was given, so instead it just defaults to using the "home scheme" installation inside the prefix that you asked for.

> This workaround solves the problem, actually:
> 
> export PYTHONPATH="$PREFIX/lib/python"
> But I wonder if we can avoid it, given that installing Broker in a Python venv should ideally not require setting this path manually.

If you don't specify `--prefix`, then I expect it installs things in a location where you don't need to set `PYTHONPATH`.

There's also the `--python-prefix` option I mentioned that I think can be used in combination with `--prefix` if you actually want the python install prefix to differ from the typical install prefix.

I'm not quite sure there's a good way to automatically disambiguate what the user wanted in this case case, but if you come up with something feel free to submit a PR, else let me know if `--python-prefix` actually doesn't work how you expect.

**Comment by mavam** [comment]
> https://docs.python.org/3.7/install/#alternate-installation-the-home-scheme

Thanks, that link cleared up things for me. 

My goal is that a user doesn't have to specify `PYTHONPATH` because I'm dealing with a virtual env that *should* be self-contained. To make this work, I needed to add a tiny script `sitecustomize.py` to `$PREFIX/lib/pythonX.Y/site-packages`:

```python
import os
import site
import sys

home = os.path.join(sys.prefix, 'lib', 'python')
site.addsitedir(home)
```

It adds the Broker prefix `$PREFIX/lib/python` to `sys.path` such that setting `PYTHONPATH` is no longer needed.
